version: '3'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    network_mode: service:postgres
    volumes:
      - ../..:/workspaces:cached
    env_file:
      - .env.development

  redis:
    image: redis:7.2-alpine
    network_mode: service:postgres

  postgres:
    image: postgres:16.2-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.development

volumes:
  pgdata: